name: Build and deploy

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:

  deploy_cratesio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true
    - name: setup cargo
      run: |
        cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
        cargo publish --manifest-path=qoqo_calculator/Cargo.toml
        sleep 60
        cargo publish --manifest-path=qoqo_calculator_pyo3/Cargo.toml

  build_maturin_builds_linux:
    name: maturin_build-linux
    needs: deploy_cratesio
    uses: ./.github/workflows/reusable_build_maturin_linux.yml
    with: 
      py_interface_folder: "qoqo_calculator_pyo3"

  build_maturin_builds_macos:
    name: maturin_build-macos
    needs: deploy_cratesio
    uses: ./.github/workflows/reusable_build_maturin_macos.yml
    with: 
      py_interface_folder: "qoqo_calculator_pyo3"

  build_maturin_builds_windows:
    name: maturin_build-windows
    needs: deploy_cratesio
    uses: ./.github/workflows/reusable_build_maturin_windows.yml
    with: 
      py_interface_folder: "qoqo_calculator_pyo3"

  publish:
    name: publish_on_pypi
    needs: [build_maturin_builds_macos, build_maturin_src_builds_linux, build_maturin_builds_linux]
    uses: ./.github/workflows/reusable_build_maturin_macos.yml
      # secrets: 
      #   pypi_api_token: ${{secrets.PYPI_API_TOKEN}}
