name: ci_tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  linting:
    uses: ./.github/workflows/reusable_linting_rust_pyo3.yml@main

  unittests:
    uses: ./.github/workflows/reusable_unittests_rust_pyo3.yml@main
    with:
      windows: true
      macos: true
      rust_package_name: "qoqo_calculator"

  build_tests:
    uses: ./.github/workflows/reusable_build_tests_rust_pyo3.yml
    with: 
      windows: true
      macos: true
      py_interface_folder: "qoqo_calculator_pyo3"
      has_python_tests: true