name: HQS build Sphinx docs for rust pyo3 repos

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish_documentation:
    uses: mlodi-hqs/reusable_workflows/.github/workflows/reusable_publish_documentation_rust_sphinx.yml@3.13_default
    with: 
      py_interface_folder: "qoqo_calculator_pyo3"
      py_docs_folder: "qoqo_calculator_pyo3/docs"
    secrets: inherit
