name: documentation

on:
  release:
    types: [created]

jobs:

  publish_documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        default: true
    - uses: Swatinem/rust-cache@v1.4.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip maturin
        pip install ./qoqo_calculator_pyo3/
        python -m pip install -r qoqo_calculator_pyo3/docs/requirements.txt
    - name: build
      run: |
        cd qoqo_calculator_pyo3/docs
        python -m sphinx -T -E -b html . _build/html
        cd ../../
    - name: publish
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./qoqo_calculator_pyo3/docs/_build/html/

  code_coverage_rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable
            components: llvm-tools-preview
            override: true
      - uses: Swatinem/rust-cache@v2.0.0
      - uses: actions/setup-python@v4.1.0
        with:
          python-version: 3.9
          cache: pip
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: |
          cd qoqo_calculator
          cargo llvm-cov --no-default-features --lcov --output-path lcov.info --fail-under-lines=89
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          # token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
    