name: documentation

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:

  publish_documentation:
    uses: .github/wokflows/reusable_unittests_rust_pyo3.yml
      with: 
        py_interface_folder: "qoqo_calculator_pyo3"
        py_docs_folder: "qoqo_calculator_pyo3/docs"
      secrets:
        tmp_github_token: ${{ secrets.GITHUB_TOKEN }}

  code_coverage_rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable
            components: llvm-tools-preview
            override: true
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: |
          cd qoqo_calculator
          cargo llvm-cov --no-default-features --lcov --output-path lcov.info --fail-under-lines=89
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          # token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
    