name: documentation

on:
  push:
    branches: [main]

jobs:

  publish_documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3.0.0
      with:
        python-version: 3.9
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        default: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip maturin
        pip install ./qoqo_calculator_pyo3/
        python -m pip install -r qoqo_calculator_pyo3/docs/requirements.txt
    - name: build
      run: |
        cd qoqo_calculator_pyo3/docs
        python -m sphinx -T -E -b html . _build/html
        cd ../../
    - name: publish
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./qoqo_calculator_pyo3/docs/_build/html/