name: reusable_publish_documentation_rust_sphinx

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      py_interface_folder:
        description: "Location of the py interface folder"
        required: true
        type: string
      py_docs_folder:
        description: "Location of the sphinx doc folder"
        required: true
        type: string
    # secrets:
    #   tmp_github_token:
    #     description: "Github token for upload"
    #     required: true
    #     type: string

jobs:

  publish_documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip maturin
        pip install ${{inputs.py_interface_folder}}/
        python -m pip install -r ${{inputs.py_docs_folder}}/requirements.txt
    - name: build
      run: |
        cd ${{inputs.py_docs_folder}}
        python -m sphinx -T -E -b html . _build/html
        cd ../../
    - name: publish
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{inputs.py_docs_folder}}/_build/html/
