name: reusable_build_maturin_macos

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      pypi_api_token:
        description: "API token for upload"
        required: true
        type: string

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - uses: actions/download-artifact@v3
        with:
          name: wheels
      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_api_token }}
        run: |
          python -m pip install --upgrade pip
          pip install twine
          python -m twine upload --skip-existing *


