name: reusable_build_maturin_linux

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      py_interface_folder:
        description: "Location of the py interface folder"
        required: true
        type: string

jobs:

  build_maturin_builds_linux:
    name: maturin_build-linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: linux wheels
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: latest
          command: build
          manylinux: 2014
          args: --find-interpreter --out wheels -m ${{inputs.py_interface_folder}}/Cargo.toml --release --locked
      - name: store artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheels

  build_maturin_builds_linux_arm:
    name: maturin_build-linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: linux wheels
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: latest
          command: build
          manylinux: 2014
          args: --find-interpreter --out wheels -m ${{inputs.py_interface_folder}}/Cargo.toml --zig --target aarch64-unknown-linux-gnu --release --locked
      - name: store artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheels

  build_maturin_src_builds_linux:
    name: maturin_build-src
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: Swatinem/rust-cache@v2.0.0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: linux wheels
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: latest
          command: sdist
          args: --out wheels -m ${{inputs.py_interface_folder}}/Cargo.toml
      - name: store artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheels
